### PR TITLE
Fix `replace!` function when replacing a `Tensor` with itself in `pair` argument

### LINKED ISSUE #225: Incorrect `replace!` of a `Tensor` in a `TensorNetwork` with the same `Tensor`
### Summary
The `replace!` function for a `Tensor` in a `TensorNetwork`, where it is replaced with the same `Tensor`, leads to the deletion of that `Tensor`:
```julia
julia> using Tenet

julia> A = Tensor(rand(2, 2, 2), (:i, :j, :k))
2×2×2 Tensor{Float64, 3, Array{Float64, 3}}: ...

julia> B = Tensor(rand(Float32, 2, 2), (:k, :j))
2×2 Tensor{Float32, 2, Matrix{Float32}}: ...

julia> tn = TensorNetwork([A, B])
TensorNetwork (#tensors=2, #inds=3)

julia> replace!(tn, A => (A))
TensorNetwork (#tensors=1, #inds=2)

julia> tensors(tn) .|> inds
1-element Vector{Vector{Symbol}}:
 [:k, :j]
```
I think that there might be a conditional in the `replace!` function that checks whether it's the same `Tensor`, and this may be causing the problem.

### PR DESCRIPTION
**Pull request by jofrevalles**
### Summary
This PR resolves #225 by fixing the problem with `replace!` when the same `Tensor` appears in both positions of the `pair` argument. Previously, since we did not have any specific check for this case, the `replace!` function had a `push!` that did not add the tensor since it was already present, but then, because we had a `delete!` after the `push!`, the `Tensor` got deleted.

We fixed this problem by adding a condition in the `replace!` function that checks if the two tensors are equal, and if they are, the function returns the `TensorNetwork` without changes.

Additionally (and importantly @bsc-quantic/software !), this PR also fixes the commented-out tests for the `replace!` function, and we have extended these tests to cover the specific case that this PR addresses.

### CODE REVIEW

File: src/TensorNetwork.jl [hunk 1]
```diff
@@ -437,6 +437,9 @@ end
 function Base.replace!(tn::AbstractTensorNetwork, pair::Pair{<:Tensor,<:Tensor})
     tn = TensorNetwork(tn)
     old_tensor, new_tensor = pair
+
+    old_tensor == new_tensor && return tn
```
Comment (mofeing) [inline src/TensorNetwork.jl:441]: mmm shouldn't this be `===` to check for egality, not equality?
```suggestion
    old_tensor === new_tensor && return tn
```

File: test/TensorNetwork_test.jl [hunk 2]
```diff
@@ -459,60 +459,75 @@
...
+                for ind in inds(new_tensor)
+                    tensors_with_ind = tn.indexmap[ind]
+                    @test new_tensor ∈ tensors_with_ind
+                    @test !(old_tensor ∈ tensors_with_ind)
+                end
             end
 
-            new_tensor = Tensor(rand(2, 2), (:l, :m))
-            replace!(tn, old_tensor => new_tensor)
+            @testset "TensorNetwork with tensors with equal indices" begin
```
Comment (mofeing) [inline test/TensorNetwork_test.jl:489]:
```suggestion
            @testset "TensorNetwork with tensors of equal indices" begin
```

File: test/TensorNetwork_test.jl [hunk 3]
```diff
@@ -459,60 +459,75 @@
...
+                replace!(tn, A => new_tensor)
 
-            # new_tensor = Tensor(rand(2, 2), (:u, :w))
+                @test issetequal(tensors(tn), [new_tensor, B])
+            end
 
-            # replace!(tn, B => new_tensor)
-            # @test A === tensors(tn)[1]
-            # @test new_tensor === tensors(tn)[2]
+            @testset "Chain of replacements" begin
```
Comment (mofeing) [inline test/TensorNetwork_test.jl:506]:
```suggestion
            @testset "Sequence of replacements" begin
```

File: test/TensorNetwork_test.jl [hunk 4]
```diff
@@ -459,60 +459,75 @@
...
-            # A = Tensor(zeros(2, 2), (:i, :j))
-            # B = Tensor(zeros(2, 2), (:j, :k))
-            # C = Tensor(zeros(2, 2), (:k, :l))
-            # tn = TensorNetwork([A, B, C])
+                replace!(tn, A => new_tensor, new_tensor => new_tensor2)
+                @test issetequal(tensors(tn), [new_tensor2, B, C])
+            end
 
-            # @test_throws ArgumentError replace!(tn, A => B, B => C, C => A)
+            @testset "Same Tensor in pair argument" begin
```
Comment (mofeing) [inline test/TensorNetwork_test.jl:521]: How about...?
```suggestion
            @testset "Replace with itself" begin
```

**Review by mofeing — CHANGES_REQUESTED** [review]

**Comment by mofeing** [comment]
Awesome! I'm leaving one import thing (egality vs equality) and some grammatical fix requests.

File: src/TensorNetwork.jl (hunk 1 above)
Comment (jofrevalles) [reply src/TensorNetwork.jl:441]: No! Since for example, now it failed when we did `replace!(tn, A => conj(A))`, when `A` is a `Tensor` with a parent `Array` that are `Real`.

Comment (mofeing) [reply src/TensorNetwork.jl:441]: Exactly! In that case, `A === conj(A)`!

Comment (jofrevalles) [reply src/TensorNetwork.jl:441]: `conj(A)` returns a new object with is equal to `A`. It would be like you say if it is `conj!` (not `conj`).

Comment (mofeing) [reply src/TensorNetwork.jl:441]: You're right with this last point, but the bug in #225 is when it's replaced with the *same* tensor (i.e. `old_tensor === new_tensor`).

I try to avoid `==` if posible because `==` iterates over the whole arrays and checks for equality element-wise, while `===` just checks the `objectid`s and you're done. Thus it avoids the overhead of iterating over everything, which can be costly on large arrays (specially when we start using distributed arrays).

Comment (jofrevalles) [reply src/TensorNetwork.jl:441]: > but the bug in #225 is when it's replaced with the _same_ tensor (i.e. `old_tensor === new_tensor`)

Yes, but I tried `replace!(tn, A => conj(A))` and we got also the same error. I think this is because if you do `conj(A)` you still get the same `objectid`, which for me this is strange:
```julia
julia> objectid(A)
0xc7798e05eba779fe

julia> objectid(conj(A))
0xc7798e05eba779fe
```

But whatever, okay! If that is the case I agree that we can have `===`, I will push that commit now.

**Comment by jofrevalles** [comment]
@mofeing I am merging this PR on monday. Let's enjoy the weekend :)
