### PR TITLE
Fix reindex! by returing the final index replace mapping

### LINKED ISSUE #177: `Tenet.@reindex` odd behavior for `mps-mpo`
Since PR #170, we have been having some problems with `Tenet.@reindex`. 

Now, I have found the following problem:
```julia
julia> mps = rand(Chain, Open, State; n=5, p=2, χ=20)
MPS (inputs=0, outputs=5)

julia> mpo = rand(Chain, Open, Operator; n=5, χ=2, p=2)
MPO (inputs=5, outputs=5)

julia> inds(mpo, at = Site(1))
:A

julia> inds(mpo, at = Site(1; dual=true))
:F

julia> Tenet.@reindex! outputs(mps) => inputs(mpo)
MPO (inputs=5, outputs=5)

julia> inds(mpo, at = Site(1))
:A

julia> inds(mpo, at = Site(1; dual=true))
:A

julia> inds.(mpo)
5-element Vector{Vector{Symbol}}:
 [:K, :V, :B, :L]
 [:L, :U, :C, :M]
 [:M, :P, :D, :N]
 [:N, :J, :E]
 [:O, :A, :K]
```

Which seems to indicate that `@reindex` is affecting to some internal of the `Chain`, but is strange since `inds.(mpo)` seems fine.

### PR DESCRIPTION
**Pull request by jofrevalles**
### Summary
This PR resolves #177 by correctly fixing the reindex of the `site` indices. To do that, we modified the `replace!` function by returning the final index mapping. I believe this is the most efficient way to do this since we could also get the mapping by comparing the tensor before and after the `replace!`, but this seems to do unnecessary work.

### Example
Now the following code works fine:
```julia
julia> mps = rand(Chain, Open, State; n=5, p=2, χ=20)
MPS (inputs=0, outputs=5)

julia> mpo = rand(Chain, Open, Operator; n=5, χ=2, p=2)
MPO (inputs=5, outputs=5)

julia> inds(mpo, at = Site(1))
:A

julia> inds(mpo, at = Site(1; dual=true))
:F

julia> Tenet.@reindex! outputs(mps) => inputs(mpo)
MPO (inputs=5, outputs=5)

julia> inds(mpo, at = Site(1))
:A

julia> inds(mpo, at = Site(1; dual=true))
:O

julia> inds.(mpo)
5-element Vector{Vector{Symbol}}:
 [:K, :V, :B, :L]
 [:L, :U, :C, :M]
 [:M, :P, :D, :N]
 [:N, :J, :E]
 [:O, :A, :K]
 
julia> contract(merge(TensorNetwork(mps), TensorNetwork(mpo))) # We get a 5-dimensional tensor as expected
2×2×2×2×2 Tensor{Float64, 5, Array{Float64, 5}}: ...
```

### CODE REVIEW

File: test/TensorNetwork_test.jl [hunk 1]
```diff
@@ -528,6 +528,27 @@
         end
     end
 
+    @testset "complicated replacement" begin
```
Comment (mofeing) [inline test/TensorNetwork_test.jl:531]:
```suggestion
    @testset "overlapping replacement" begin
```

File: test/TensorNetwork_test.jl [hunk 2]
```diff
@@ -528,6 +528,27 @@
...
+
+        replace!(tn, old_new...)
+
+        # issetequal to this
+        # [:O, :A, :K]
+        # [:K, :V, :B, :L]
+        # [:L, :U, :C, :M]
+        # [:M, :P, :D, :N]
+        # [:N, :J, :E]
+        @test issetequal(vcat(collect(values(tn.tensormap))...), vcat([[:O, :A, :K], [:K, :V, :B, :L], [:L, :U, :C, :M], [:M, :P, :D, :N], [:N, :J, :E]]...))
```
Comment (mofeing) [inline test/TensorNetwork_test.jl:549]: Use `inds.(tensors(tn))` or another way to test this.

**Review by mofeing — APPROVED** [review]
